# Generated by Django 2.0.6 on 2018-10-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(),
        ),
    ]
