# Generated by Django 2.0.6 on 2018-10-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='db_deleted_timestmap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='db_deleted_timestmap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
