# Generated by Django 2.0.6 on 2018-10-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
