# Generated by Django 2.0.6 on 2018-10-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20181013_0719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='db_deleted_timestmap',
            new_name='db_deleted_timestamp',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='db_deleted_timestmap',
            new_name='db_deleted_timestamp',
        ),
    ]
