# Generated by Django 2.0.6 on 2018-06-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('backend_api', '0003_auto_20180617_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuuid',
            new_name='uuid',
        ),
    ]
