# Generated by Django 2.0.6 on 2019-02-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20181013_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.TextField(default='https://image.flaticon.com/icons/svg/149/149071.svg'),
        ),
    ]
