# Generated by Django 2.0.6 on 2018-06-17 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20180617_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_api.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
