# Generated by Django 2.0.6 on 2018-06-17 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_auto_20180617_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='backend_api.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend_api.User'),
        ),
    ]
