# Generated by Django 2.0.6 on 2018-08-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_auto_20180617_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.TextField(default='group'),
            preserve_default=False,
        ),
    ]
