# Generated by Django 2.0.6 on 2018-08-05 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0011_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatmapping',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
