# Generated by Django 2.0.6 on 2018-08-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_auto_20180812_1834'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userchatmapping',
            unique_together={('user_one', 'user_two')},
        ),
    ]
