# Generated by Django 2.0.6 on 2018-09-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0018_auto_20180922_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
